### ISSUE TITLE
pitch preservation when changing playback rate

### ISSUE THREAD

**Issue by eniac314** [MartinSStewart/elm-audio#15]
I am trying to add controls to my player to slowdown the playback speed. It works but the pitch gets lower as well. 
I would like to keep the pitch the same at different speeds. 
Is there a way to do this?

**Comment by eniac314** [comment]
I found this which seems to be relevant but I don't know how to apply it
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/preservesPitch

**Comment by MartinSStewart** [comment]
Hi, sorry about the slow response. The link you posted is for audio tags (https://package.elm-lang.org/packages/elm/html/latest/Html#audio) which isn't compatible with this package. This package uses the web audio API which doesn't directly support changing playback rate while preserving pitch.

If you just want to make a music player then maybe it's better to use audio tags instead? They give you less control over the exact timing of the sound which is an issue for playing sound effects in a game but maybe isn't an issue for a music player.

**Comment by eniac314** [comment]
Oh I see, too bad. The slowdown feature is not too critical. 
Your library was a good fit for the other needs I had, I'll keep the player the way it is for now.
Thank you!
