### ISSUE TITLE
Errors and 404s

### ISSUE THREAD

**Issue by psycotica0** [MartinSStewart/elm-audio#2]
Hello!

I'm playing around with this library and ran up against an unexpected issue.

I tried loading a non-existent URI, and rather than getting an `Audio.LoadError`, instead I get nothing.

I traced through the code looking for the issue, and this is what I found:

1. It's not calling the error callback of `XMLHttpRequest`, because the page is returning data (with a status code of 404). That data isn't audio data, though. Theoretically we could check the status code here and return a `NotFound` error and that would fix my problem, but there are other deeper problems to follow
2. The 404 response has a body, it's just that the body isn't audio data. So it's being passed to `decodeAudioData`. The assumption seems to be here that if it's audio, who cares about the status, and if it's not then we'll throw an error in the error callback, which is what happens in this case.
3. The root of the issue: The error handling [here](https://github.com/MartinSStewart/elm-audio/blob/3.0.3/src/Audio.elm#L550-L557) has an explicit case statement of errors it expects, followed by an `else` that declares anything else a JSON parse error. This is the case I'm hitting. I'm in Firefox 82.0, and the exception [going into](https://github.com/MartinSStewart/elm-audio/blob/3.0.3/src/audio.js#L44) the handler has the message:
  
       The buffer passed to decodeAudioData contains an unknown content type.

So, a few things:
First, the exception has other properties that may be more consistent than `message` if you're planning on doing a case statement for all "real" errors. It looks like, on my browser at least, it has `name: "EncodingError"`, which may be safer? It's listed in [these docs](https://developer.mozilla.org/en-US/docs/Web/API/DOMException#Error_names), but I'm not sure about how widespread it is.

But more importantly, JSON parse errors are [consumed by the library](https://github.com/MartinSStewart/elm-audio/blob/3.0.3/src/Audio.elm#L533-L534), and so my application will never be told about this issue. It seems like a 404 is one of the things I'm most likely to experience when loading external audio, and the fact that the library basically stalls my app here is a bit unfortunate.

I mean, there isn't necessarily a lot I can do in this case necessarily, but I could at least put my app into an error state and thus tell the user something was broken, or maybe I could move past whatever loading screen I was on and just not play those sounds. But right now, from my app's perspective, it just never loads.

I expect there's a reason we wanted the `LoadError` to be so explicit, but it feels like a `| OtherError String` or something would be better in this case than treating any error except these two as a JSON parse error, or at least in some way getting this error to be a load error for my request.

Thanks!

**Comment by MartinSStewart** [comment]
Thanks for the detailed commit and sorry about now seeing it earlier. I'll take a closer look at this tonight.

**Comment by MartinSStewart** [comment]
Thanks again for the bug report.

It looks like I'll need to handle more error cases and have a `UnknownError` to default to instead of tossing the error away. If you need a solution now I think you can get around this problem by using the unminified version of the JS code and replacing line 44 with `app.ports.audioPortFromJS.send({ type: 0, requestId: requestId, error: "MediaDecodeAudioDataUnknownContentType" });`. That should give you the `MediaDecodeAudioDataUnknownContentType` back.

> I expect there's a reason we wanted the `LoadError` to be so explicit, but it feels like a `| OtherError String` or something would be better in this case than treating any error except these two as a JSON parse error, or at least in some way getting this error to be a load error for my request.

Unfortunately adding `| OtherError String` won't be possible. I need to stick to adding custom type variants that don't have any parameters (or at least only parameters with a small number of possible values). I can give a full explanation of why if you're interested but the short of it is that it's related to why I have a `ErrorThatHappensWhenYouLoadMoreThan1000SoundsDueToHackyWorkAroundToMakeThisPackageBehaveMoreLikeAnEffectPackage` variant.

**Comment by psycotica0** [comment]
Hey! No worries, I'm not really in any rush. Once I figured out what the issue _actually_ was, I just fixed it so it was no longer pointing at an invalid URI :sweat_smile: 

I'll believe you on the error handling and trust you'll make whatever the right call is, now that you've seen the issue. Thanks!

**Comment by MartinSStewart** [comment]
This is now fixed in 4.0.0. I haven't added any new error messages (I might go back and do that at some point) but loading an audio source should never silently fail.
