### ISSUE TITLE
Get the length of an audio source

### ISSUE THREAD

**Issue by DXsmiley** [MartinSStewart/elm-audio#3]
Is there currently a way to get the length of an audio source (in seconds) ? I can't see anything in the documentation.

**Comment by MartinSStewart** [comment]
Currently there is not, you need to hard code the duration. That said, this is something I've fixed in a newer unreleased version. Do you need this issue addressed soon?

**Comment by DXsmiley** [comment]
I can live with hard coding the during for the moment.

**Comment by MartinSStewart** [comment]
Fixed now. You can get the length of an audio source with `Audio.length`.
