### ISSUE TITLE
An example for a looping sound would help me and others

### ISSUE THREAD

**Issue by PixelPartner** [MartinSStewart/elm-audio#5]
I found the documentation how to set up looping, but no example how to invoke/use it after loading a sound.

**Comment by MartinSStewart** [comment]
Sure, I'll write up an example here later today and if you think it's clear then I'll add it to the documentation. Sound good?

**Comment by MartinSStewart** [comment]
I had a look at the existing documentation first and remembered that there's this. Did this not make sense or was there something else you were having trouble with?
```elm
{-| Control how audio loops. `loopEnd` defines where (relative to the start of the audio) the audio should loop and `loopStart` defines where it should loop to.

    -- Here we have a song that plays an intro once and then loops between the 10 second point and the end of the song.
    let
        default =
            Audio.audioDefaultConfig

        -- This package doesn't support getting how long a sound plays for so we need to hard code it instead.
        songLength =
            Duration.seconds 120
    in
    audioWithConfig
        { default | loop = Just { loopStart = Duration.seconds 10, loopEnd = songLength } }
        coolBackgroundMusic
        startTime

-}
type alias LoopConfig =
    { loopStart : Duration, loopEnd : Duration }
```

**Comment by PixelPartner** [comment]
What's missing for me is how to invoke the loadAudio with this custom config

**Comment by MartinSStewart** [comment]
Okay, I think I see a misunderstanding. `loadAudio` doesn't need any config. When you want to play that audio however, then you provide the custom config to make the audio loop.

Here's a modified version of the ellie example in the readme to show what I mean https://ellie-app.com/dsDbfTgJPBma1 (the changes I've made are on lines 126 to 140). The music playing should play until it reaches the 5 second mark and then loop back to the 2 second mark.

Does this make sense?

**Comment by PixelPartner** [comment]
Thank you very much, that helped a lot and solved my case.

**Comment by MartinSStewart** [comment]
Awesome, I'll see if I can think of a good way to explain this in the documentation.

**Comment by PixelPartner** [comment]
How about introducing a loopAfter30secs checkbox and use the default in the else case

Von meinem iPad gesendet
